apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: plugins.dashboard.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes/kubernetes/pull/78458"  
spec:
  group: dashboard.k8s.io
  scope: Namespaced
  names:
    kind: Plugin
    plural: plugins
    singular: plugin
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                source:
                  type: object
                  properties:
                    configMapRef:
                      type: object
                      properties:
                        name:
                          type: string
                      required:
                        - name
                    filename:
                      type: string
                  required:
                    - configMapRef
                    - filename
                dependencies:
                  type: array
                  items:
                    type: string
              required:
                - source
          required:
            - spec
      served: true
      storage: true
